language: php
php:
- 5.5
env:
- MAGENTO_VERSION=magento-ce-1.9.2.4
before_script:
- TAG=$(git describe --abbrev=0)
- export VERSION=${TAG:1}
- echo Building version $VERSION
- tar cf package.tar app/ js/ lib/ skin/
- git clone --recursive https://github.com/astorm/MagentoTarToConnect.git /tmp/MagentoTarToConnect
- sed -i s/%%VERSION%%/${VERSION}/g build.php
script:
- php /tmp/MagentoTarToConnect/magento-tar-to-connect.php build.php
before_deploy:
- export PACKAGE=$(ls *.tgz)
- echo "Deploying $PACKAGE"
deploy:
  provider: releases
  api_key:
    secure: aYrq5ME5r7ohbHnv9WBouxYzeBe7TPDXt+SOecrGp/xdwOuW6IBpBliNraSjmltguuqfBtrqrgGIssaKVsPz4YahfLih4KaG1Mff01zh6BhLWFcKZyW1ketkVt+isg57xBGL8L+RU5ttM7oPQvcNasm9g0heO6NfKmBube5Rfw7+frxwDhjn608sahZdd4XR/R1ESoZqW0Ov6IhZj7+xlylLU9wV8Fk6kPYnflCVtWwRI1/E8VuQAfX81QKFF2+v8u4ekS/oVYBXMOEADj9e3vUS5PiKi+i44MKA2UAXMdUq0qIeIry2V1C+mz5JQQX5sDpSMg9+DvePOtBMPEDAiNt72nImB9QBUyqqSJGUVA21sXxh3P2MMKb1i9ZSQMIKz+5J1XmEyTbVINkK2ztKF4JsTa/bKJf4K4DkJjioJvstnK72mUR2Q5kQ36P7s/mbEtFj6MIq94iRQaNkCWvUyJR/hoaxW+OVJ0B9Nz2QLYZD9xqHBJrdBCHF6Tqt6P4oviHhCGm4YvEOHBplr7XGRSJqzghU9negKSmIRWVKAwyAOYn/U+3M/8jOmq2ZV38lbn+Nng7mzvIWoMTuKkCJbcafdhND4YTyKgAVM08fw5THXKfW8sLhg108rDrinkRO2K8PUQ+yoLav/37RJegk/PUEIw8U33+ccgFwc9FNyRQ=
  file:
   - "${PACKAGE}"
  on:
   repo: fjbender/magento-1
   all_branches: true
   tags: true
notifications:
  email: false
  # todo slack

